### ISSUE TITLE
Merging fails

### ISSUE THREAD

**Issue by andischan** [mapbox/geojson-merge#16]
I've installed with npm -g install @mapbox/geojson-merge:

`/usr/lib/node_modules/@mapbox/geojson-merge/geojson-merge:15
  process.stdout.write(JSON.stringify(merge(argv._.map(function(n) {
                                      ^

TypeError: merge is not a function
    at Object.<anonymous> (/usr/lib/node_modules/@mapbox/geojson-merge/geojson-merge:15:39)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3`

**Comment by tmcw** [comment]
Sorry about that - 1.0.1 is now released. If you reinstall or force install of 1.0.1 this issue should be fixed.
