### ISSUE TITLE
Error when combining two geo .json files

### ISSUE THREAD

**Issue by britboyjohnson** [mapbox/geojson-merge#20]
[paul.zip](https://github.com/mapbox/geojson-merge/files/1011830/paul.zip)

I'm trying to merge the above two files and get the following error 
C:\Node\node_modules>node .bin/geojson-merge GB.json de.json > c:\node\node_modules\out.json
C:\Node\node_modules\.bin\geojson-merge:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)

**Comment by andrewharvey** [comment]
That doesn't appear to be coming from geojson-merge. Perhaps try updating your version of node? That line looks Linux specific, which might be a problem running on windows.
