### ISSUE TITLE
running geojson-merge on wildcard (*.geojson)

### ISSUE THREAD

**Issue by aatishb** [mapbox/geojson-merge#37]
Hi, I just installed geojson-merge, and when I try ` geojson-merge *.geojson` in a folder with some geojson files, I get the following error:

```
undefined:1


SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /Users/aatish/.nvm/versions/node/v14.20.0/lib/node_modules/@mapbox/geojson-merge/geojson-merge:18:19
    at Array.map (<anonymous>)
    at Object.<anonymous> (/Users/aatish/.nvm/versions/node/v14.20.0/lib/node_modules/@mapbox/geojson-merge/geojson-merge:17:52)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47

```

Appreciate any help with this.

**Comment by aatishb** [comment]
never mind, it worked after deleting the output and trying again! the issue seems to be I was including the combined geojson as one of the input files.
